export const videogames = [
  {
    title: "Resident Evil 4 Remake",
    platform: "Xbox Series X",
    image: "https://m.media-amazon.com/images/I/71YYP0Sz31L._SX342_.jpg",
    tags: ["action", "horror", "survival", "third-person"],
    score: 4.2,
    vendor: [
      {
        vendorId: "GamerPro1",
        price: 9099,
        state: "Nuevo",
        condition: "Sólo Disco y/o Manual",
        sponsored: true,
      },
      {
        vendorId: "GamerPro2",
        price: 5129,
        state: "Usado",
        condition: "Completo",
        sponsored: false,
      },
      {
        vendorId: "GamerPro3",
        price: 7162,
        state: "Buen estado",
        condition: "Completo",
        sponsored: false,
      },
    ],
  },
  {
    title: "Dark Souls III: The Fire Fades Edition (GOTY)",
    platform: "PS4",
    image: "https://m.media-amazon.com/images/I/616p1i6gfxL._AC_SX679_.jpg",
    tags: ["action", "horror", "survival", "third-person"],
    score: 4.9,
    vendor: [
      {
        vendorId: "R4 Games Store",
        price: 799,
        state: "Excelente Estado",
        condition: "Completo",
        stock: 1,
        discount: 0.3,
        sponsored: true,
        protected: true,
        verified: true,
      },
      {
        vendorId: "GamerPro1",
        price: 650,
        state: "Nuevo",
        condition: "Completo",
        sponsored: false,
        verified: true,
        stock: 1,
        discount: 0,
      },
      {
        vendorId: "GamerPro2",
        price: 450,
        state: "Usado",
        condition: "Completo",
        sponsored: false,
        stock: 1,
        discount: 0.5,
      },
      {
        vendorId: "GamerPro3",
        price: 918,
        state: "Buen estado",
        condition: "Completo",
        sponsored: false,
        stock: 1,
        discount: 0,
      },
    ],
  },
  {
    title: "Death Stranding: Director's Cut",
    platform: "Xbox Series X",
    image: "https://m.media-amazon.com/images/I/71YYP0Sz31L._SX342_.jpg",
    tags: ["action", "horror", "survival", "third-person"],
    score: 4.1,
    vendor: [
      {
        vendorId: "ABDHSDJHDFSFHJKSFKJ",
        price: 799,
        state: "Excelente Estado",
        condition: "Completo",
        sponsored: true,
      },
    ],
  },
  {
    title: "Naruto Shippuden: Ultimate Ninja Storm 4 Road To Boruto",
    platform: "Xbox Series X",
    image: "https://m.media-amazon.com/images/I/71YYP0Sz31L._SX342_.jpg",
    tags: ["action", "horror", "survival", "third-person"],
    score: 2.8,
    vendor: [
      {
        vendorId: "ABDHSDJHDFSFHJKSFKJ",
        price: 799,
        state: "Excelente Estado",
        condition: "Completo",
        sponsored: true,
      },
    ],
  },
  {
    title: "Resident Evil 6",
    platform: "Xbox Series X",
    image: "https://m.media-amazon.com/images/I/71YYP0Sz31L._SX342_.jpg",
    tags: ["action", "horror", "survival", "third-person"],
    score: 2.2,
    vendor: [
      {
        vendorId: "ABDHSDJHDFSFHJKSFKJ",
        price: 799,
        state: "Excelente Estado",
        condition: "Completo",
        sponsored: true,
      },
    ],
  },
  {
    title: "Resident Evil 4 Remake",
    platform: "Xbox Series X",
    image: "https://m.media-amazon.com/images/I/71YYP0Sz31L._SX342_.jpg",
    tags: ["action", "horror", "survival", "third-person"],
    score: 4.7,
    vendor: [
      {
        vendorId: "ABDHSDJHDFSFHJKSFKJ",
        price: 799,
        state: "Excelente Estado",
        condition: "Completo",
        sponsored: true,
      },
    ],
  },
  {
    title: "Resident Evil 4 Remake",
    platform: "Xbox Series X",
    image: "https://m.media-amazon.com/images/I/71YYP0Sz31L._SX342_.jpg",
    tags: ["action", "horror", "survival", "third-person"],
    score: 3.8,
    vendor: [
      {
        vendorId: "ABDHSDJHDFSFHJKSFKJ",
        price: 799,
        state: "Nuevo",
        condition: "Completo",
        sponsored: true,
      },
    ],
  },
  {
    title: "Resident Evil 4 Remake",
    platform: "Xbox Series X",
    image: "https://m.media-amazon.com/images/I/71YYP0Sz31L._SX342_.jpg",
    tags: ["action", "horror", "survival", "third-person"],
    score: 4.7,
    vendor: [
      {
        vendorId: "ABDHSDJHDFSFHJKSFKJ",
        price: 799,
        state: "Excelente Estado",
        condition: "Completo",
        sponsored: true,
      },
    ],
  },
  {
    title: "Resident Evil 4 Remake",
    platform: "Xbox Series X",
    image: "https://m.media-amazon.com/images/I/71YYP0Sz31L._SX342_.jpg",
    tags: ["action", "horror", "survival", "third-person"],
    score: 2.5,
    vendor: [
      {
        vendorId: "ABDHSDJHDFSFHJKSFKJ",
        price: 799,
        state: "Excelente Estado",
        condition: "Buen Estado",
        sponsored: true,
      },
    ],
  },
];
